/*
---
githubHandle: brianwachira

---
*/

#define INTRO1 "\nI am here to guide you on choosing a career.\nI may ask you some questions.I need you to answer them so that I may know how to guide you.\nI hope you are good with that.\n\nType 'Y' to continue or 'N' to exit.\n\n"

#define EMPLOYMENT "Ok.Congratulations for getting a degree your life. Welcome to the\njob sector. First things first,there is value in friendship.\nThe campus friend you have might be the one signing up\naudits for you while your working. If your thinking of self\nemployment,he might be the person funding it. The guy you\nused to pay lunch for you in campus might be the\nnext billionaire. You never know. Continue building in friendships. Other\nthan that you are a freshman or woman in the market.\nYou need to build your rating. You need to gain\nthe trust of your colleagues. Always remember that\n"

#define CHANGE  "I acknowledge you are making a hard decision. I respect that.\nI hope you have considered all factors for example the cost of changing\n your career, the span of time it will take for you to\ndo that and many other factors.If you have made your final decision,\nthen it is ok. However, think about it.\n"

#define HIGHSCHOOL "It is ok. You should know that, it is good\nto be young. Rejoice in your youth. However,Picture this:\nYou have a painting board,painting brush and different paints.\nYour asked to paint a car. The image is in the\nmind so the strokes go inline with what is in your\nmind. If you stroke patiently and apply the right stress then\nyour art will turn out fabulous. However if you rush and\nmess up, you end up with a mediocre kind of art.\n Now the painting board is your future. Your dreams and visions are in your mind. If you rush with your plans,you might\n lose it all. Patience is the key. You will get there.Patience\nis key.Focus on whats beneficial.\n\nYou are going to be succesful.\nAlways know, you are a success.\nThat is the far we will interact.\nUntil next time "

#define ACCOUNTING "I hope you love maths because this path requires accuracy in counting.\nAnyway, if you follow this path,below is what you can become:\n\t\t-An Accountant\n\t\t-An Accounting clerk\n\t\t-Accounting manager\n\t\t-Budget analyst\n\t\t-A Certified Internal Auditor.\n\n\tThe courses you can pursue for higher learning include;\n\t\t-Accounting\n\t\t-Accounting Technology\n\t\t-Actuarial science\n\t\t-Finance\n\nWith that you are sure to be on the right place.\nHowever please research more on this field."

#define MARKETING "You do seem to sweet tongue.\nI bet your one social person.\nAnyway,Some careers you can land on in this field include:\n\t\t-Public Relations Manager\n\t\t-Market Research Analyst\n\t\t-Advertising Manager\n\t\t-Media buyer\n\t\t-Meeting,Convention & Event Planner\n\nThe courses you can consider for higher learning is a Bachelor of Marketing with a focus on advertising, marketing and communication"

#define I_BUSINESS "Your a person has a wide scope of thinking. That is good.\nYou can become:\nAn International accountant\nA international economist\nA Managemant Analyst\nYou can also major on internatiomal banking.\n\nIn this field consider to do a course called International Business.\nIt will put you on the airwaves"

#define P_ARTS "This mostly involves publicity (You Vs The World)\nYou can pursue Music or Drama. If you want to pursue music,here  is what you can become:\n\t\t-Singer \n\t\t-Talent scout\n\t\t-Composer\n\t\tConcert promoter\n\nIf you want to pursue drama,here is what you can become:\n\t\t-Actor\n\t\tStage manager\n\t\tArts Admin\n\t\tA Drama Teacher\n\t\tDrama Therapist.\n\n"

#define C_ARTS "\nWho doesnt love the kitchen? Especially if you don't know how to cook.\nJust kidding.\nAnyway this is what your gifted hands can make you to become:\n\t\t-A Chef\n\t\t-Caterer\n\t\t-Restuarant cook\n\t\tExecutive chef\n\t\tFood and beverage manager\nSome of the courses you can pursue in higher learning include;\n\t\t-Catering\n\t\t-Professional baking and pastry\n\t\t-Food Research\n\t\t-Food Sales & Marketing\n\t\t-Hospitality Management\n\n"

#define V_ARTS "\nVisual arts is wide.\nSince I could not tell you everything about it, I recommend you research more on this.\nThis are some of the careers in visual arts:\n\t\t-Photo Journalist\n\t\t-Graphic Designer\n\t\t-Production Artist\n\t\t-Art Dealer\n\t\t-Art Historian\n\n"

#define P_SCIENCE "\nPhysical science refers to a scientific field that involves the study of non-living things,\nsuch as matter and energy.\nCommon fields in the physical sciences include:\n\t\t-physics\n\t\t-chemistry\n\t\t-geology and astronomy\n\nYou could choose from a wide variety of associate's and bachelor's degree programs\nin the physical sciences. For example, you could obtain an Associate of Science (A.S.) in Physics\nor an Associate of Applied Science (A.A.S.) in Chemical Technology.\nCommon bachelor's degree programs you could choose from include;\n\t-astronomy and astrophysics\n\t-geology and geophysics\n\t-earth science\n\tphysics and chemistry.\n\nIf you choose to pursue a career in chemistry, you'll also have the option of conducting research\nin pharmaceutical, chemical, biotech, petroleum and other consumer products industries.\nOn the other hand, if you choose to become a materials scientist, you could find employment with\ncompanies that manufacture plastics and other polymers, semiconductors, electronics and chemicals.\nIf you choose the physics route, you could work for companies that design and manufacture lasers,\nimaging equipment and other scientific instruments, as well as looking for opportunities with\ndefense contractors and companies that sell data-analysis software. As a physicist or astronomer,\nyou could also conduct\nresearch at national labs or federal government agencies, such as the National Aeronautics and Space Administration ."

#define E_SCIENCE "\nEarth Sciences graduates work in a wide variety of jobs, all over the world—on land and at sea.\nWith a Bachelor of Science (BSc) in Earth Sciences, you could find a position in a number of exciting sectors and industries.you can become:\n\t\tenvironmental consultant\n\t\tgroundwater specialist\n\t\tmining or marine engineer\n\t\tenvironmental scientist\n\t\tgeologist or marine geologist\n\t\tpaleontologist\n\t\tpetroleum geologist\n\t\tgeochemist\n\t\tgeophysicist\n\t\toceanographer\n\t\tenvironmental lawyer\n"

#define L_SCIENCE "\nIt goes without saying that people who work in life sciences really know what life is all about...So, if you’ve got a head for science and you’re fascinated by life and all its scientific processes, you should definitely consider a career in this subsector!\n\nEssentially, you’ll be working in laboratories to help increase scientific understanding of genetics, fertility, plant life and the cause and development of diseases (a.k.a. pathology).\nFurthermore, you will be conducting vital research studies and experiments to help doctors diagnose illnesses and treat people in the best possible way.\n\nIf you pursue a career in this area, you will most likely be working in:\n\t\t-hospital labs\n\t\t-academic institutions\n\t\t-clinics\n\t\tpharmaceutical companies or specialist clinical research organisations.\n\nThis is a massively broad area of work and the clinical research scientists that work in the life sciences arena are employed in many different niche roles.\n\nYou could become a clinical biochemist and spend you’re your time analysing blood, semen, saliva and urine samples\n\nyou could pursue a career as a toxicologist and investigate the effects of chemicals, drugs and other substances on humans.\n\nAlternatively, you could become an embryologist, where you’d be using techniques such as IVF treatment to help people with infertility problems.\n\nYou could be working in the morgue as a pathologist to determine causes of death\n\nYou could become a cytogeneticist who investigates hereditary diseases\n\nYou could develop a career as an immunologist who studies AIDS, HIV, transplant rejection and other problems that relate to the immune system."

#define ENGINEERING "\nEngineering is interesting and exciting. People may see that it involves tedious stuff but if your fully into this then you might not get exhausted as other people are.\nIt is a quite lucrative career path by the way.\nSome of the options of career paths in this field include:\n\t\t-Chemical Engineering\n\t\t-Electrical Engineering\n\t\t-Civil & Structural Engineering\n\t\tEnvironmental Engineering\n "

#define C_TECHNOLOGY "\nThis is the fastest growing career field.\nYou may be branded outdated if you dont keep yourself at par with the emerging trends.\nDevelop a learning plan with the necessary skills such as computer training and\nIT certification to build a competitive edge and achieve your goals.\nSome of the persons you can be include:\n\n-Data scientist\t\t\t\t-IT project manager\n-Computer hardware engineer\t\t-Computer Architect\n-Robotics Engineer\t\t\t-IT manager\n-Mobile App developer\t\t\t-Computer programmer\n-System Analyst\t\t\t\t-Software Engineer\n-Graphic Designer\t\t\t-Web Developer\n\nSome of the courses you can pursue in higher learning include;\n\n\t-Computer Science\n\t-Applied Computer Science\n\t-Computer programming\n\t-Information Technology\n\t-Software Engineering\n"

#define DEGREE1 "When you consider pursuing a higher level of\neducation in your interested field,your advised to start with\n a degree certification.However, your level of competence grows as\nyou climb up the ladder of certification.Hence, if you\nseek employment and feel like you need to be paid\nmore than what your being paid, you need to upgrade\nyour certification to either a master or a Phd.\n\nIt is you to choose.\n"

#define DEGREE2 "When you consider pursuing a higher level of\neducation in your interested field, your advised with a degree.\nIf your grade can't allow you to pursue a degree,\nthen you can start with the allowed field in that course.\nAs you move to the job market, you may be\npaid according to your level of certification.Hence if you\nfeel like your being paid less then what you need\nis to further your studies in that field.\n\nThe higher the certification then the higher your paid.\n"

#define DIPLOMA3 "When you are considering to pursue a higher\nlevel of education in your interested field, you may have\nto start from diploma certification.However this may not be\nthe case for you if taking degree with your grade\nis allowed.As you move to the job market,you may\nbe paid according to your level of certification.Hence, if you\nfeel like your salary needs to be increased then you\nmay need to further your studies in that field.\n"

#define CERTIFICATE4 "When you are considering to pursue a higher\nlevel of education in your interested field, you may only\nbe allowed to start from certificate level of certification.\nDo not be dismayed;apply the right diligence and you\nmay find yourself at the top. As you find yourself\nin the job market, you may be paid according to your level of certification. Hence may need to further your\nstudies for your wage to be increased.\n\nThe higher the certification then the higher your paid.\n"

#define employee "You need to be the best out there. You need\n to be excellent in what you do.Build on your strengths.\nKnow your weaknesses and learn how to deal with them.\nGain skills that will help you be recognized in the job market.\n"

#define s_employed "You need to be sure of what you are presenting to\nthe market.will it sustain you in your career?\nWill you be circumstancially out of the market in the few years from now?\nAre you really into this,in times when your life is\nlike a movie script and when your life is like one of\nthose good gone bad articles on magazines?"
